
server:
  port: 9081
  session-timeout: 60

spring:
    redis:
      lettuce:
        pool:
          max-idle: 10
          in-idle: 5
          max-active: 100
      database: 0
      host: 127.0.0.1
      port: 6379
      ext:
        nodes[0]:
          host: 127.0.0.1
          port: 6379
          database: 0



#  spring.redis.lettuce.pool.max-idle=10
#  spring.redis.lettuce.pool.min-idle=5
#  spring.redis.lettuce.pool.max-active=100
#  spring.redis.database=0
#  spring.redis.host=192.168.139.129
#  spring.redis.port=6379
#  spring.redis.ext.nodes[0].host=192.168.139.129
#  spring.redis.ext.nodes[0].port=6379
#  spring.redis.ext.nodes[0].password=
#  spring.redis.ext.nodes[0].database=0
mysql:
    datasource:
        readSize: 1  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:mapper/*.xml
        configLocation: classpath:/mybatis-config.xml
        write:
           url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=utf-8
           username: root
           password: w3d56yu8r
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:
           url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=utf-8
           username: root
           password: w3d56yu8r
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
    